### ISSUE TITLE
Segmentation fault in igbinary.so

### ISSUE THREAD

**Issue by szepeviktor** [igbinary/igbinary7#5]
gdb told me:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa3d6a47c41 in igbinary_serialize_ex () from /usr/lib/php/20151012/igbinary.so
```

The binary is available here
http://packages.dotdeb.org/pool/all/p/php-igbinary/

What could be the cause?

**Comment by TysonAndre** [comment]
Various bugs have been fixed since then.
http://packages.dotdeb.org

I'd suggest building igbinary7 yourself, or waiting for @gplessis to package the newest version of igbinary7's master branch. (The package was updated since this issue was filed, but before this comment)

 clone the master branch of the igbinary7 repository: https://github.com/igbinary/igbinary7 (No alpha yet on pecl)

``` bash
# Optionally set CFLAGS, etc.
phpize
./configure --with-php-config=`which php-config`
make
# make test
sudo make install
cd ..
```

If you continue to have problems, please include a php script to reproduce the bug, expected output, and actual output.

**Comment by szepeviktor** [comment]
Thank you.
I would be waiting for @gplessis

**Comment by gplessis** [comment]
Thanks for the heads up!

FYI up-to-date packages [have been built](https://ci.dotdeb.org/job/dotdeb-php-igbinary/job/jessie-php70/lastSuccessfulBuild/). I'll publish them soon. Don't hesitate to give me your feedback.
